### ISSUE TITLE
EXC_BAD_ACCESS in createPairs

### ISSUE THREAD

**Issue by BabyAzerty** [daltoniam/SwiftHTTP#222] opened 2016-04-15 14:18 UTC
In the function createPairs, I have a EXC_BAD_ACCESS at this line:
`else if let subParam = nestedVal as? Array<AnyObject> {
                    collect.appendContentsOf(subParam.createPairs(useKey))
                } `

Here are the variables when it crashes
[![Variables](http://i.imgur.com/owJAx0n.png)](http://i.imgur.com/owJAx0n.png)

This are my parameters:
`["offices": ["570d4d4ca1f5d2e994d5295d", "570d4d4ca1f5d2e994d5295c"], "departments": []]`

I call it this way: 
`let opt = try HTTP.POST(request.URL!.absoluteString, parameters: ["offices": offices, "departments": departments], headers: request.allHTTPHeaderFields)`

**Comment by acmacalister** [comment] 2016-05-01 04:33
@BabyAzerty did you try the solution suggested in #155?

**Comment by BabyAzerty** [comment] 2016-05-01 10:21
Yes it didn't work.
So I had 2 cases where it bugs. The one from the initial post which is not even a mix case of params. And a case where params is mixed with array, string & int

**Comment by isno** [comment] 2016-05-01 10:42
I have the same problem.  everything is ok  when I use iOS simulator  ! but when the app upload to apple store, this problem appears.

**Comment by isno** [comment] 2016-05-01 10:43
#155
@acmacalister it didn't work!

**Comment by bertrandserres** [comment] 2016-06-28 17:21
Any update about this bug ?
I'm releasing my app and I'm struggling with this error. As isno said, there's no problem when running app with "Debug" Build configuration and it's only crashing when using "Release" Build configuration

**Comment by daltoniam** [comment] 2016-07-09 05:05
This is actually a duplicate of #223 which has a bit more debug work in it so I am going to merge this one with that one. This appears to be a bug in the Swift compiler for the way `createPairs` is being done and using protocols. I plan to address this in the Swift 3 release, but PRs are welcomed as I haven't had time much time to investigate this.

**Closed by daltoniam** 2016-07-09 05:05 UTC
